services:
  - type: web
    name: chamahub-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    healthCheckPath: /api/users
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chamahub-db
          property: connectionString
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

databases:
  - name: chamahub-db
    databaseName: chamahub
    user: chamahub_user
    plan: free
